/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import alertas.ErrorAlert;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import rojeru_san.rspanel.RSPanelsSlider;

/**
 *
 * @author RojeruSan
 */
public class pnlVentasPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form pnlVentasPrincipal
     */
    public pnlVentasPrincipal() {
        initComponents();

        addEventKey();
    }

    private void addEventKey() {
        //--------------------------------------------------------------------------------
        KeyStroke f5 = KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0, false);
        Action f5Action = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                if (!btnVentas.isSelected()) {
                    btnVentas.setSelected(true);
                    btnReportes.setSelected(false);
                    btnUltimasVentas.setSelected(false);
                    btnDevoluciones.setSelected(false);

                    pnlSlider.setPanelSlider(1, pnlVentas1, RSPanelsSlider.DIRECT.RIGHT);
                }
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(f5, "F5");
        this.getActionMap().put("F5", f5Action);

        //--------------------------------------------------------------------------------
        KeyStroke f6 = KeyStroke.getKeyStroke(KeyEvent.VK_F6, 0, false);
        Action f6Action = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                if (!btnReportes.isSelected()) {
                    btnVentas.setSelected(false);
                    btnReportes.setSelected(true);
                    btnUltimasVentas.setSelected(false);
                    btnDevoluciones.setSelected(false);

                    pnlSlider.setPanelSlider(1, pnlReportes1, RSPanelsSlider.DIRECT.RIGHT);
                }
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(f6, "F6");
        this.getActionMap().put("F6", f6Action);

        //--------------------------------------------------------------------------------
        KeyStroke f7 = KeyStroke.getKeyStroke(KeyEvent.VK_F7, 0, false);
        Action f7Action = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                if (!btnUltimasVentas.isSelected()) {
                    btnVentas.setSelected(false);
                    btnReportes.setSelected(false);
                    btnUltimasVentas.setSelected(true);
                    btnDevoluciones.setSelected(false);

                    pnlSlider.setPanelSlider(1, pnlVentasToDay1, RSPanelsSlider.DIRECT.RIGHT);
                }
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(f7, "F7");
        this.getActionMap().put("F7", f7Action);
        
        //--------------------------------------------------------------------------------
        KeyStroke f8 = KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0, false);
        Action f8Action = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                if (!btnDevoluciones.isSelected()) {
                    btnVentas.setSelected(false);
                    btnReportes.setSelected(false);
                    btnUltimasVentas.setSelected(false);
                    btnDevoluciones.setSelected(true);

                    pnlSlider.setPanelSlider(1, pnlDevoluciones1, RSPanelsSlider.DIRECT.RIGHT);
                }
            }
        };
        this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(f8, "F8");
        this.getActionMap().put("F8", f8Action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnReportes = new rojeru_san.RSButtonRiple();
        btnUltimasVentas = new rojeru_san.RSButtonRiple();
        btnVentas = new rojeru_san.RSButtonRiple();
        btnDevoluciones = new rojeru_san.RSButtonRiple();
        pnlSlider = new rojeru_san.rspanel.RSPanelsSlider();
        pnlVentas1 = new principal.pnlVentas();
        pnlReportes1 = new ventas.pnlReportes();
        pnlVentasToDay1 = new ventas.pnlVentasToDay();
        pnlDevoluciones1 = new ventas.pnlDevoluciones();

        setBackground(new java.awt.Color(255, 255, 255));

        btnReportes.setBackground(new java.awt.Color(69, 87, 252));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas/btnReporte.png"))); // NOI18N
        btnReportes.setText("Reportes (F6)");
        btnReportes.setColorHover(new java.awt.Color(173, 187, 194));
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnUltimasVentas.setBackground(new java.awt.Color(69, 87, 252));
        btnUltimasVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas/lblUltimas.png"))); // NOI18N
        btnUltimasVentas.setText("Últimas ventas (F7)");
        btnUltimasVentas.setColorHover(new java.awt.Color(173, 187, 194));
        btnUltimasVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUltimasVentas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUltimasVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimasVentasActionPerformed(evt);
            }
        });

        btnVentas.setBackground(new java.awt.Color(69, 87, 252));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas/btnCobrar.png"))); // NOI18N
        btnVentas.setText("Caja(F5)");
        btnVentas.setColorHover(new java.awt.Color(173, 187, 194));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVentas.setSelected(true);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnDevoluciones.setBackground(new java.awt.Color(69, 87, 252));
        btnDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas/btn-devolucion.png"))); // NOI18N
        btnDevoluciones.setColorHover(new java.awt.Color(173, 187, 194));
        btnDevoluciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDevoluciones.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDevoluciones.setLabel("Devoluciones (F8)");
        btnDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnUltimasVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnUltimasVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlVentas1.setName("pnlVentas1"); // NOI18N
        pnlSlider.add(pnlVentas1, "card2");

        pnlReportes1.setName("pnlReportes1"); // NOI18N
        pnlSlider.add(pnlReportes1, "card3");

        pnlVentasToDay1.setName("pnlVentasToDay1"); // NOI18N
        pnlSlider.add(pnlVentasToDay1, "card4");

        pnlDevoluciones1.setName("pnlDevoluciones1"); // NOI18N
        pnlSlider.add(pnlDevoluciones1, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 534, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        if (privilegios.Operaciones.ReportesVentas(principal.Principal.lblID.getText())) {
            if (!this.btnReportes.isSelected()) {
                this.btnVentas.setSelected(false);
                this.btnReportes.setSelected(true);
                this.btnUltimasVentas.setSelected(false);
                this.btnDevoluciones.setSelected(false);

                this.pnlSlider.setPanelSlider(1, pnlReportes1, RSPanelsSlider.DIRECT.RIGHT);
            }
        } else {
            ErrorAlert e = new ErrorAlert(new JFrame(), true);
            e.msj1.setText("No cuentas con los privilegios");
            e.msj2.setText("para acceder a esta opción.");
            e.msj3.setText("");
            e.setVisible(true);
        }
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnUltimasVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimasVentasActionPerformed
        if (privilegios.Operaciones.UltimasVentas(principal.Principal.lblID.getText())) {
            if (!this.btnUltimasVentas.isSelected()) {
                this.btnVentas.setSelected(false);
                this.btnReportes.setSelected(false);
                this.btnUltimasVentas.setSelected(true);
                this.btnDevoluciones.setSelected(false);

                this.pnlSlider.setPanelSlider(1, pnlVentasToDay1, RSPanelsSlider.DIRECT.RIGHT);
            }
        } else {
            ErrorAlert e = new ErrorAlert(new JFrame(), true);
            e.msj1.setText("No cuentas con los privilegios");
            e.msj2.setText("para acceder a esta opción.");
            e.msj3.setText("");
            e.setVisible(true);
        }
    }//GEN-LAST:event_btnUltimasVentasActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        if (privilegios.Operaciones.RegistrarVentas(principal.Principal.lblID.getText())) {
            if (!this.btnVentas.isSelected()) {
                this.btnVentas.setSelected(true);
                this.btnReportes.setSelected(false);
                this.btnUltimasVentas.setSelected(false);
                this.btnDevoluciones.setSelected(false);

                this.pnlSlider.setPanelSlider(1, pnlVentas1, RSPanelsSlider.DIRECT.RIGHT);
            }
        } else {
            ErrorAlert e = new ErrorAlert(new JFrame(), true);
            e.msj1.setText("No cuentas con los privilegios");
            e.msj2.setText("para acceder a esta opción.");
            e.msj3.setText("");
            e.setVisible(true);
        }
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionesActionPerformed
        if (!this.btnDevoluciones.isSelected()) {
                this.btnVentas.setSelected(false);
                this.btnReportes.setSelected(false);
                this.btnUltimasVentas.setSelected(false);
                this.btnDevoluciones.setSelected(true);

                this.pnlSlider.setPanelSlider(1, pnlDevoluciones1, RSPanelsSlider.DIRECT.RIGHT);
            }
    }//GEN-LAST:event_btnDevolucionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnDevoluciones;
    private rojeru_san.RSButtonRiple btnReportes;
    private rojeru_san.RSButtonRiple btnUltimasVentas;
    private rojeru_san.RSButtonRiple btnVentas;
    private javax.swing.JPanel jPanel3;
    private ventas.pnlDevoluciones pnlDevoluciones1;
    private ventas.pnlReportes pnlReportes1;
    private rojeru_san.rspanel.RSPanelsSlider pnlSlider;
    private principal.pnlVentas pnlVentas1;
    private ventas.pnlVentasToDay pnlVentasToDay1;
    // End of variables declaration//GEN-END:variables
}
