/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import about.pnlAbout;
import alertas.WarningAlert;
import configuracion.pnlConfiguracion;
import static java.awt.Frame.ICONIFIED;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import librerias.RSTool;
import licencia.Ejecutar;
import licencia.Verificar;
import rojeru_san.complementos.RSUtilities;
import rojeru_san.rspanel.RSPanelsSlider;

/**
 *
 * @author RojeruSan
 */
public class Principal extends javax.swing.JFrame {

    private boolean minimiza = false;

    /**
     * Creates new form Principal1
     */
    public Principal() {
        initComponents();

        this.setTitle("SAIVLine - Punto de venta");

        RSUtilities.setIconoVentana(this, "/img/principal/iconoHD.png");
        this.setExtendedState(MAXIMIZED_BOTH);
        
        this.lblID.setVisible(false);
        
        verificaLicencia();
        
        setToolTip();
        
        pnlConfiguracion.ventana(this);
    }

    public static void verificaLicencia(){
        if (Verificar.existePrueva()) {
            lblDias.setText(Ejecutar.diasRestantes + " días");
        }else{
            lblDias.setText("");
            lbl1.setText("");
            lbl2.setText("");
            btnLicencia.setVisible(false);
            
            pnlAbout.verificaLicencia();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlSlider = new rojeru_san.rspanel.RSPanelsSlider();
        pnlVentasPrincipal1 = new principal.pnlVentasPrincipal();
        pnlAlmacen1 = new almacen.pnlAlmacen();
        pnlUsuarios1 = new usuarios.pnlUsuarios();
        pnlConfiguracion1 = new configuracion.pnlConfiguracion();
        pnlAbout1 = new about.pnlAbout();
        lblUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        btnLicencia = new rojeru_san.RSButtonRiple();
        lbl2 = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAlmacen = new rojeru_san.RSButtonRiple();
        btnVentas = new rojeru_san.RSButtonRiple();
        btnUsuarios = new rojeru_san.RSButtonRiple();
        btnConfiguración = new rojeru_san.RSButtonRiple();
        btnAbout = new rojeru_san.RSButtonRiple();
        btnCerrar = new rojeru_san.rsbutton.RSButtonMetro();
        btnMin = new rojeru_san.rsbutton.RSButtonMetro();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlSlider.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        pnlVentasPrincipal1.setName("pnlVentasPrincipal1"); // NOI18N
        pnlSlider.add(pnlVentasPrincipal1, "card5");

        pnlAlmacen1.setName("pnlAlmacen1"); // NOI18N
        pnlSlider.add(pnlAlmacen1, "card3");

        pnlUsuarios1.setName("pnlUsuarios1"); // NOI18N
        pnlSlider.add(pnlUsuarios1, "card4");

        pnlConfiguracion1.setName("pnlConfiguracion1"); // NOI18N
        pnlSlider.add(pnlConfiguracion1, "card5");

        pnlAbout1.setName("pnlAbout1"); // NOI18N
        pnlSlider.add(pnlAbout1, "card6");

        lblUsuario.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(109, 109, 109));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuario.setText("USUARIO");
        lblUsuario.setToolTipText("CAMBIAR DE USUARIO");
        lblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUsuarioMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 112, 192));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/lblConectado.png"))); // NOI18N

        lblID.setText("ID");

        btnLicencia.setBackground(new java.awt.Color(0, 204, 102));
        btnLicencia.setText("ACTIVAR");
        btnLicencia.setColorHover(new java.awt.Color(173, 187, 194));
        btnLicencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLicencia.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciaActionPerformed(evt);
            }
        });

        lbl2.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        lbl2.setForeground(new java.awt.Color(171, 179, 182));
        lbl2.setText("de prueba");

        lblDias.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        lblDias.setForeground(new java.awt.Color(243, 66, 53));
        lblDias.setText("15 días");

        lbl1.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        lbl1.setForeground(new java.awt.Color(171, 179, 182));
        lbl1.setText("Le quedan");

        jPanel2.setBackground(new java.awt.Color(69, 87, 252));

        jPanel3.setBackground(new java.awt.Color(69, 87, 252));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(173, 187, 194)));

        btnAlmacen.setBackground(new java.awt.Color(69, 87, 252));
        btnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/btnProductos.png"))); // NOI18N
        btnAlmacen.setText("ALMACEN");
        btnAlmacen.setColorHover(new java.awt.Color(173, 187, 194));
        btnAlmacen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlmacen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenActionPerformed(evt);
            }
        });

        btnVentas.setBackground(new java.awt.Color(69, 87, 252));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/btnVentas.png"))); // NOI18N
        btnVentas.setText("VENTAS");
        btnVentas.setColorHover(new java.awt.Color(173, 187, 194));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVentas.setSelected(true);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(69, 87, 252));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new/usuarios.png"))); // NOI18N
        btnUsuarios.setText("CAJEROS");
        btnUsuarios.setColorHover(new java.awt.Color(173, 187, 194));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnConfiguración.setBackground(new java.awt.Color(69, 87, 252));
        btnConfiguración.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new/config.png"))); // NOI18N
        btnConfiguración.setText("CONFIGURACIÓN");
        btnConfiguración.setColorHover(new java.awt.Color(173, 187, 194));
        btnConfiguración.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConfiguración.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConfiguración.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguraciónActionPerformed(evt);
            }
        });

        btnAbout.setBackground(new java.awt.Color(69, 87, 252));
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/btnAcercaDe.png"))); // NOI18N
        btnAbout.setText("SOPORTE");
        btnAbout.setColorHover(new java.awt.Color(173, 187, 194));
        btnAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnConfiguración, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnConfiguración, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnCerrar.setBackground(new java.awt.Color(69, 87, 252));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/btn-cerrar.png"))); // NOI18N
        btnCerrar.setGrosorLinea(1);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(69, 87, 252));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/btn-minimizar.png"))); // NOI18N
        btnMin.setToolTipText("");
        btnMin.setGrosorLinea(1);
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("P u n t o  de  V e n t a");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/logoSAIVLite.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblID))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 482, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLicencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenActionPerformed
        if (!this.btnAlmacen.isSelected()) {
            this.btnAlmacen.setSelected(true);
            this.btnVentas.setSelected(false);
            this.btnUsuarios.setSelected(false);
            this.btnConfiguración.setSelected(false);
            this.btnAbout.setSelected(false);

            this.pnlSlider.setPanelSlider(1, pnlAlmacen1, RSPanelsSlider.DIRECT.DOWN);
        }
    }//GEN-LAST:event_btnAlmacenActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        if (!this.btnUsuarios.isSelected()) {
            this.btnAlmacen.setSelected(false);
            this.btnVentas.setSelected(false);
            this.btnUsuarios.setSelected(true);
            this.btnConfiguración.setSelected(false);
            this.btnAbout.setSelected(false);

            this.pnlSlider.setPanelSlider(1, pnlUsuarios1, RSPanelsSlider.DIRECT.DOWN);
        }
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnConfiguraciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguraciónActionPerformed
        if (!this.btnConfiguración.isSelected()) {
            this.btnAlmacen.setSelected(false);
            this.btnVentas.setSelected(false);
            this.btnUsuarios.setSelected(false);
            this.btnConfiguración.setSelected(true);
            this.btnAbout.setSelected(false);

            this.pnlSlider.setPanelSlider(1, pnlConfiguracion1, RSPanelsSlider.DIRECT.DOWN);
        }
    }//GEN-LAST:event_btnConfiguraciónActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        if (!this.btnAbout.isSelected()) {
            this.btnAlmacen.setSelected(false);
            this.btnVentas.setSelected(false);
            this.btnUsuarios.setSelected(false);
            this.btnConfiguración.setSelected(false);
            this.btnAbout.setSelected(true);

            this.pnlSlider.setPanelSlider(1, pnlAbout1, RSPanelsSlider.DIRECT.DOWN);
        }
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        if (!this.btnVentas.isSelected()) {
            this.btnAlmacen.setSelected(false);
            this.btnVentas.setSelected(true);
            this.btnUsuarios.setSelected(false);
            this.btnConfiguración.setSelected(false);
            this.btnAbout.setSelected(false);

            this.pnlSlider.setPanelSlider(1, pnlVentasPrincipal1, RSPanelsSlider.DIRECT.DOWN);
        }
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        WarningAlert w = new WarningAlert(this, true);
        w.msj1.setText("Salir de la aplicación...");
        w.msj2.setText("");
        w.msj3.setText("");
        w.accion = "Salir";
        w.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        this.setExtendedState(ICONIFIED);
        if (!minimiza) {
            minimiza = false;
            this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        } else {
            minimiza = true;
        }
    }//GEN-LAST:event_btnMinActionPerformed

    private void lblUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMousePressed
        this.dispose();
        new login.Login().setVisible(true);
    }//GEN-LAST:event_lblUsuarioMousePressed

    private void btnLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciaActionPerformed
        new licencia.Activar(this, true).setVisible(true);
    }//GEN-LAST:event_btnLicenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnAbout;
    private rojeru_san.RSButtonRiple btnAlmacen;
    private rojeru_san.rsbutton.RSButtonMetro btnCerrar;
    private rojeru_san.RSButtonRiple btnConfiguración;
    public static rojeru_san.RSButtonRiple btnLicencia;
    private rojeru_san.rsbutton.RSButtonMetro btnMin;
    private rojeru_san.RSButtonRiple btnUsuarios;
    private rojeru_san.RSButtonRiple btnVentas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lbl1;
    public static javax.swing.JLabel lbl2;
    public static javax.swing.JLabel lblDias;
    public static javax.swing.JLabel lblID;
    public static javax.swing.JLabel lblUsuario;
    private about.pnlAbout pnlAbout1;
    private almacen.pnlAlmacen pnlAlmacen1;
    private configuracion.pnlConfiguracion pnlConfiguracion1;
    private rojeru_san.rspanel.RSPanelsSlider pnlSlider;
    private usuarios.pnlUsuarios pnlUsuarios1;
    private principal.pnlVentasPrincipal pnlVentasPrincipal1;
    // End of variables declaration//GEN-END:variables

    private void setToolTip() {
        lblUsuario.setToolTipText(RSTool.head+RSTool.body+"Cambiar de usuario"+RSTool.pie);
    }
}
