/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actualizar;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import rojeru_san.complementos.RSUtilities;

/**
 *
 * @author Rojeru San
 */
public class VerificaUpdate extends javax.swing.JDialog {

    private boolean versionActual = false;

    /**
     * Creates new form Error
     *
     * @param parent
     * @param modal
     */
    public VerificaUpdate(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        RSUtilities.setCentrarVentana(this);
        RSUtilities.setOpaqueVentana(this, false);
        this.setLocationRelativeTo(parent);

        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(5000);

                    if (new Actualizacion().isConexionInternet()) {

                        if (!new Actualizacion().getVersion().equals("1.0")) {
                            versionActual = false;
                        } else {
                            lblVersion.setText("Versión " + new Actualizacion().getVersion() + " disponible.");
                            versionActual = true;
                        }

                        if (versionActual) {
                            pnlSlider.setPanelSlider(1, pnlActual, rojeru_san.rspanel.RSPanelsSlider.DIRECT.RIGHT);
                        } else {
                            pnlSlider.setPanelSlider(1, pnlDescargar, rojeru_san.rspanel.RSPanelsSlider.DIRECT.RIGHT);
                        }
                    } else {
                        pnlSlider.setPanelSlider(1, pnlError, rojeru_san.rspanel.RSPanelsSlider.DIRECT.RIGHT);
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(VerificaUpdate.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.rspanel.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        pnlSlider = new rojeru_san.rspanel.RSPanelsSlider();
        pnlVerificar = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        rSProgressMaterial1 = new rojeru_san.rsprogress.RSProgressMaterial();
        titulo3 = new javax.swing.JLabel();
        btnCerrar1 = new rojeru_san.rsbutton.RSButtonEffect();
        pnlActual = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        btnCerrar2 = new rojeru_san.rsbutton.RSButtonEffect();
        pnlError = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        titulo4 = new javax.swing.JLabel();
        btnCerrar3 = new rojeru_san.rsbutton.RSButtonEffect();
        pnlDescargar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        btnDescargar = new rojeru_san.rsbutton.RSButtonEffect();
        btnCerrar4 = new rojeru_san.rsbutton.RSButtonEffect();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(69, 87, 252));

        pnlVerificar.setBackground(new java.awt.Color(69, 87, 252));
        pnlVerificar.setName("pnlVerificar"); // NOI18N

        titulo.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Buscando");

        rSProgressMaterial1.setForeground(new java.awt.Color(255, 255, 255));
        rSProgressMaterial1.setAnchoProgress(15);

        titulo3.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        titulo3.setForeground(new java.awt.Color(255, 255, 255));
        titulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo3.setText("actualización...");

        btnCerrar1.setBackground(new java.awt.Color(69, 87, 252));
        btnCerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actualizar/boton-cerrar.png"))); // NOI18N
        btnCerrar1.setColorHover(new java.awt.Color(69, 87, 252));
        btnCerrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVerificarLayout = new javax.swing.GroupLayout(pnlVerificar);
        pnlVerificar.setLayout(pnlVerificarLayout);
        pnlVerificarLayout.setHorizontalGroup(
            pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerificarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(rSProgressMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVerificarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlVerificarLayout.setVerticalGroup(
            pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlVerificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVerificarLayout.createSequentialGroup()
                        .addComponent(titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titulo3)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVerificarLayout.createSequentialGroup()
                        .addComponent(rSProgressMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );

        pnlSlider.add(pnlVerificar, "card2");

        pnlActual.setBackground(new java.awt.Color(69, 87, 252));
        pnlActual.setName("pnlActual"); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actualizar/lblActualizado.png"))); // NOI18N

        titulo1.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("¡Aplicación actualizada!");

        btnCerrar2.setBackground(new java.awt.Color(69, 87, 252));
        btnCerrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actualizar/boton-cerrar.png"))); // NOI18N
        btnCerrar2.setColorHover(new java.awt.Color(69, 87, 252));
        btnCerrar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlActualLayout = new javax.swing.GroupLayout(pnlActual);
        pnlActual.setLayout(pnlActualLayout);
        pnlActualLayout.setHorizontalGroup(
            pnlActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnCerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlActualLayout.setVerticalGroup(
            pnlActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualLayout.createSequentialGroup()
                .addGroup(pnlActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(pnlActualLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlSlider.add(pnlActual, "card3");

        pnlError.setBackground(new java.awt.Color(69, 87, 252));
        pnlError.setName("pnlDescargar"); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actualizar/label-error.png"))); // NOI18N

        titulo4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        titulo4.setForeground(new java.awt.Color(255, 255, 255));
        titulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo4.setText("¡Verifica tu conexión a internet!");

        btnCerrar3.setBackground(new java.awt.Color(69, 87, 252));
        btnCerrar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actualizar/boton-cerrar.png"))); // NOI18N
        btnCerrar3.setColorHover(new java.awt.Color(69, 87, 252));
        btnCerrar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlErrorLayout = new javax.swing.GroupLayout(pnlError);
        pnlError.setLayout(pnlErrorLayout);
        pnlErrorLayout.setHorizontalGroup(
            pnlErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo4, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlErrorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnCerrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlErrorLayout.setVerticalGroup(
            pnlErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlErrorLayout.createSequentialGroup()
                .addGroup(pnlErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlErrorLayout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(pnlErrorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCerrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(titulo4)
                .addGap(28, 28, 28))
        );

        pnlSlider.add(pnlError, "card4");

        pnlDescargar.setBackground(new java.awt.Color(69, 87, 252));
        pnlDescargar.setName("pnlDescargar"); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actualizar/label-warnign.png"))); // NOI18N

        titulo2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 255));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("¡Existe una nueva actualización!");

        lblVersion.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText("Versión 1.1 disponible.");

        btnDescargar.setBackground(new java.awt.Color(255, 255, 255));
        btnDescargar.setForeground(new java.awt.Color(0, 0, 0));
        btnDescargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actualizar/btnDescargar.png"))); // NOI18N
        btnDescargar.setText("Descargar actualización");
        btnDescargar.setColorHover(new java.awt.Color(255, 255, 255));
        btnDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarActionPerformed(evt);
            }
        });

        btnCerrar4.setBackground(new java.awt.Color(69, 87, 252));
        btnCerrar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actualizar/boton-cerrar.png"))); // NOI18N
        btnCerrar4.setColorHover(new java.awt.Color(69, 87, 252));
        btnCerrar4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDescargarLayout = new javax.swing.GroupLayout(pnlDescargar);
        pnlDescargar.setLayout(pnlDescargarLayout);
        pnlDescargarLayout.setHorizontalGroup(
            pnlDescargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDescargarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDescargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(lblVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDescargarLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(pnlDescargarLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnDescargar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDescargarLayout.setVerticalGroup(
            pnlDescargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDescargarLayout.createSequentialGroup()
                .addGroup(pnlDescargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDescargarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCerrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVersion)
                .addGap(18, 18, 18)
                .addComponent(btnDescargar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSlider.add(pnlDescargar, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 195, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://github.com/RojeruSan/Archivos"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(VerificaUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnDescargarActionPerformed

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    private void btnCerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrar2ActionPerformed

    private void btnCerrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrar3ActionPerformed

    private void btnCerrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerificaUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerificaUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerificaUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerificaUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerificaUpdate dialog = new VerificaUpdate(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsbutton.RSButtonEffect btnCerrar1;
    private rojeru_san.rsbutton.RSButtonEffect btnCerrar2;
    private rojeru_san.rsbutton.RSButtonEffect btnCerrar3;
    private rojeru_san.rsbutton.RSButtonEffect btnCerrar4;
    private rojeru_san.rsbutton.RSButtonEffect btnDescargar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblVersion;
    private javax.swing.JPanel pnlActual;
    private javax.swing.JPanel pnlDescargar;
    private javax.swing.JPanel pnlError;
    private rojeru_san.rspanel.RSPanelsSlider pnlSlider;
    private javax.swing.JPanel pnlVerificar;
    private rojeru_san.rspanel.RSPanelShadow rSPanelShadow1;
    private rojeru_san.rsprogress.RSProgressMaterial rSProgressMaterial1;
    public static javax.swing.JLabel titulo;
    public static javax.swing.JLabel titulo1;
    public static javax.swing.JLabel titulo2;
    public static javax.swing.JLabel titulo3;
    public static javax.swing.JLabel titulo4;
    // End of variables declaration//GEN-END:variables
}
